#!/bin/sh

set -eu

test_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
work_dir=$(mktemp -d "${TMPDIR:-/tmp}/hvjp2k-transcode-test.XXXXXX")
trap 'rm -rf "$work_dir"' EXIT

if [ -n "${HVJP2K_BIN:-}" ]; then
    transcode="$HVJP2K_BIN/hv_jp2_transcode"
else
    transcode=hv_jp2_transcode
fi

name=2015_12_21__00_10_34_34__SDO_AIA_AIA_171.jp2
cp "$test_dir/orig/$name" "$work_dir/$name"
"$transcode" -d "$work_dir" --xml-rewrite
cmp "$work_dir/$name" "$test_dir/trans/$name"
echo "pass: $name"
