#!/bin/sh

set -eu

test_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
work_dir=$(mktemp -d "${TMPDIR:-/tmp}/hvjp2k-jp2-test.XXXXXX")
trap 'rm -rf "$work_dir"' EXIT

if [ -n "${HVJP2K_BIN:-}" ]; then
    decode="$HVJP2K_BIN/hv_jp2_decode"
else
    decode=hv_jp2_decode
fi

name=2010_04_01__00_00_28__PROBA2_SWAP_SWAP_174
"$decode" -i "$test_dir/$name.jp2" -o "$work_dir/$name.ppm" \
    -region '{0.6,0.1},{0.3,0.5}' -reduce 2
cmp "$work_dir/$name.ppm" "$test_dir/$name.ppm"
echo "pass: $name.jp2"
